### ISSUE TITLE
Unclear license

### ISSUE THREAD

**Issue by richardpl** [kakaroto/libsiren#1]
The COPYING file is LGPL 2.1 while license in every other file header i looked is GPL.

**Comment by kakaroto** [comment]
You're mistaken. I looked at every .c and .h file and they all specify LGPL 'version 2 or later' and the COPYING file is LGPL 2.1.
I'm not so great with my understanding of licenses, and I don't know the difference between LGPL 2 and LGPL 2.1 but since 2.1 is "later" than 2 and the license in the files say "version 2 or later", then I don't see the problem here.

**Comment by richardpl** [comment]
.c/.h files have Library instead of Lesser.

**Comment by kakaroto** [comment]
It's the same thing.
EDIT: You said the .c/.h files state "GPL", but that's not the case, "Library GPL" and "Lesser GPL" are both the "LGPL". You can even read about the name change in the COPYING file : 
```
[This is the first released version of the Lesser GPL.  It also counts
 as the successor of the GNU Library Public License, version 2, hence
 the version number 2.1.]
```

**Comment by richardpl** [comment]
Thanks for clear explanation, I'm really sorry for wasting your time.

**Comment by kakaroto** [comment]
No worries, glad I could make it clear (usually, i'm the one confused and lost when it comes to licenses)!
I'm curious btw, what are you using libsiren for ?

**Comment by richardpl** [comment]
I'm looking to porting this code to FFmpeg for audio stream in old vivo 2 files.

**Comment by kakaroto** [comment]
Ok, cool! 
There's a GstSiren codec in GStreamer, you could look at it for example on how to use the library, it might help, and there also seems to be a couple of fixes (wrong samplerate in common.c and remove static variables in decoder.c/encoder.c) : 
https://github.com/GStreamer/gst-plugins-bad/tree/master/gst/siren
